import { CrawlerComponentStatus } from "./CrawlerComponentStatus";
import { NodeStatus } from "./NodeStatus";

// This file was generated by TypeWriter. Do not modify.
export interface ComponentStatus {
    
    tasksInUse: number;
    maxConcurrentTasks: number;
    queueCount: number;
    currentStatus: CrawlerComponentStatus;
    nodeStatus: NodeStatus;
}