import { ComponentStatsBase } from "./ComponentStatsBase";


// This file was generated by TypeWriter. Do not modify.
export interface CompletedItemStats extends ComponentStatsBase {
    
    totalBytesIngestedSinceLastUpdate: number | null;
    totalBytesIngested: number | null;
    recentItems: any[];
}