import { ComponentStatsBase } from "./ComponentStatsBase";


// This file was generated by TypeWriter. Do not modify.
export interface CompletedItemStats extends ComponentStatsBase {
    
    totalBytesSinceLastUpdate: number | null;
    totalBytes: number | null;
    recentItems: any[];
}