import { IErrorCode } from "./IErrorCode";
import { ComponentStatsBase } from "./ComponentStatsBase";


// This file was generated by TypeWriter. Do not modify.
export interface FailedItemStats extends ComponentStatsBase {
    
    errorCounts: { [key: string]: number; };
    recentItems: IErrorCode[];
}