import { RequestBase } from "./RequestBase";


// This file was generated by TypeWriter. Do not modify.
export interface IngestRequest extends RequestBase {
    
    currentCrawlDepth: number;
    maxDepthReached: boolean;
}