import { HttpStatusCode } from "./HttpStatusCode";
import { RedirectResult } from "./RedirectResult";
import { IngestFailureReason } from "./IngestFailureReason";
// This file was generated by TypeWriter. Do not modify.
export interface IngestFailure {
    
    uri: string;
    requestStartTime: Date;
    timeTaken: string;
    httpStatusCode: HttpStatusCode | null;
    mediaType: string | null;
    redirects: RedirectResult[];
    error: IngestFailureReason;
}