

// This file was generated by TypeWriter. Do not modify.
export interface NodeStatusStats {
    
    totalBytesDownloaded: number;
    totalBytesUploaded: number;
    totalBytesDownloadedSinceLastUpdate: number;
    totalBytesUploadedSinceLastUpdate: number;
}