import { RequestBase } from "./RequestBase";


// This file was generated by TypeWriter. Do not modify.
export interface ParseRequest extends RequestBase {
    
    contentId: string;
    currentCrawlDepth: number;
}