import { HttpStatusCode } from "./HttpStatusCode";
// This file was generated by TypeWriter. Do not modify.
export interface RedirectResult {
    
    destinationUri: string;
    redirectStatusCode: HttpStatusCode;
}