name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./DistributedWebCrawler.sln
    - name: Build
      run: dotnet build ./DistributedWebCrawler.sln --no-restore
    - name: Test
      run: dotnet test ./DistributedWebCrawler.sln --no-build --filter "Category!=Integration" --verbosity normal
